CREATE DATABASE IF NOT EXISTS compta2;
USE compta2;

-- Table des fournisseurs
CREATE TABLE IF NOT EXISTS FOURNISSEUR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255) NOT NULL
);

-- Table des articles
CREATE TABLE IF NOT EXISTS ARTICLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REF VARCHAR(50) NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    PRIX DECIMAL(10, 2) NOT NULL,
    ID_FOU INT,
    CONSTRAINT fk_article_fournisseur
        FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

-- Table des bons de commande
CREATE TABLE IF NOT EXISTS BON (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(50) NOT NULL,
    DATE_CMDE DATE NOT NULL,
    DELAI INT,
    ID_FOU INT,
    CONSTRAINT fk_bon_fournisseur
        FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

-- Table de composition des bons
CREATE TABLE IF NOT EXISTS COMPO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QTE INT NOT NULL,
    ID_ART INT,
    ID_BON INT,
    CONSTRAINT fk_compo_article
        FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID),
    CONSTRAINT fk_compo_bon
        FOREIGN KEY (ID_BON) REFERENCES BON(ID)
);